### ISSUE TITLE
option for logarithmic axes

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#10]
**@mhandreae** requested an option to change axes to logarithmic scale in the bivariate plot

**Comment by bob-carpenter** [comment]
This is a very good idea because Stan really samples
on the unconstrained scale.  So if you have a positive
constrained parameter theta, it samples log theta.

For parameters constrained to (0,1), it uses the log-odds
(logit) transform, and that may also be helpful in plotting.

These can potentially be negated (upper bounds instead of
lower bound), shifted (upper or lower bounds other than 0),
or scaled (range other than (0,1)).

I have no idea what to do for the multivariate cases.

All of this is covered in the later variable transform chapter
of the manual.

**Comment by jgabry** [comment]
Included in branch prep_1.1.0 and will be part of next release
