### ISSUE TITLE
as.shinystan throws error when fed list of matrices without colnames

### ISSUE THREAD

**Issue by saudiwin** [stan-dev/shinystan#104]
This is a simple to fix but surprisingly frustrating bug. As.shinystan expects any lists of matrices of mcmc output to have column names; if it doesn't, it will throw an uninformative error regarding subscripts out of range:

Error in out[, i, ] <- chain_list[[i]] : 
  number of items to replace is not a multiple of replacement length

An easy fix is to put in a check for colnames in the chains2shinystan() and then to generate colnames for the matrices via an lapply/paste0 combination.

I don't have a fully replicable example, but if that is necessary I can provide one.

**Comment by jgabry** [comment]
Thanks for reporting the error. Should be resolved by ac33187 and will be in the next release. 

I decided to make the error message more informative rather than forcing the column names to some default uninformative names if they're missing. I'd rather have parameter names be required, but at least now it will inform the user that this is the problem rather than reporting the useless error message you were seeing.

**Comment by saudiwin** [comment]
Sounds good to me.

Bob
