### ISSUE TITLE
Rhat over time

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#11]
From **@mhandreae**:

Could we have a plot of Rhat over time to assess convergence over time and consider an appropriate burn-in or compare model efficiency? Compare with Kruschke's diagMCMC, lower left plot.

Copied from original issue: jgabry/SHINYstan#11

**Comment by bob-carpenter** [comment]
That would be a fun algorithm.  We could probably use a
Welford-type algorithm for R-hat.  n_eff would be too
prohibitive as that involves a fast (everything is relative)
Fourier transform to compute the autocorrelation at each lag.

- Bob

**Comment by andrewgelman** [comment]
It’s just a little tricky because the splits in split R-hat change in each step. But I guess that can be computed fast if it’s coded carefully.  We can also step back and say we just need R-hat and n_eff every 100 iterations, not every iteration.
And of course this is also a chance to think more about Ben’s recommendations for convergence monitoring.
A

**Comment by bob-carpenter** [comment]
It's straightforward with Welford's algorithm modified to
allow deletion:

  http://lingpipe-blog.com/2009/07/07/welford-s-algorithm-delete-online-mean-variance-deviation/

In Stan-like pseudocode, with a Welford accumulator implementation:

```
vector x;
accumulator accum_prefix;
accumulator accum_suffix;

for (n in 1:size(x)) {
  accum_suffix.add(x[n]);
  if (n is even) {
    accum_suffix.delete(x[n/2]);
    accum_prefix.add(x[n/2]);
  }
  ... now you have the sufficient stats you need ...
}
```

- Bob

**Comment by jgabry** [comment]
Cool! I'd never seen Welford's algorithm before.
