### ISSUE TITLE
Message when using `launch_shinystan`

### ISSUE THREAD

**Issue by csgillespie** [stan-dev/shinystan#118]
Currently when you launch shiny, the terminal displays:

```
Loading... 
Note: for large models ShinyStan may take a few moments to launch.
```

Is it worthwhile giving another message when shinyStan is up and running, e.g.

```
ShinyStan is ready to go
```

**Comment by jgabry** [comment]
Yeah I tried that at some point, but it's a bit tricky. For example, if `x` is a stanfit object then `launch_shinystan(x)` (a) converts `x` to a shinystan object and (b) launches the app. For large models it takes some time to do both (a) and (b) but from within `launch_shinystan` it's only really possible to alert the user that (a) has finished. So we could have an extra message after the shinystan object is created internally but it will still take additional time for the app to launch and render properly. I decided not to include the message about (a) because I thought people would interpret it as (a) and (b) and then wonder why it still hadn't launched properly yet. And it's tricky to explain this in a quick message. But if you have a better idea I'm all ears!
