### ISSUE TITLE
Freezing R on error or closing tab

### ISSUE THREAD

**Issue by colemonnahan** [stan-dev/shinystan#133]
I use Chrome with shinystan, and I've noticed two cases where my R session locks up. The first is when I forget to "Close and Save" on the browser and just close the tab. The second is if there is an error when calling `launch_shinystan`. In both cases my R terminal remains unresponsive with "Listening on...".

It would be nice not to have to restart R (and rerun the models!) in these cases.

**Comment by jgabry** [comment]
Thanks for reporting this. A few comments below:

On Fri, Sep 9, 2016 at 5:46 PM, Cole Monnahan <notifications@github.com>
wrote:

> I use Chrome with shinystan, and I've noticed two cases where my R session
> locks up. The first is when I forget to "Close and Save" on the browser.
>
Are you using RStudio? If so you should be able to click the red "Stop"
button and it will unlock your R session. If you're not using RStudio then
you should be able to use the escape key on your keyboard.

> The second is if there is an error when calling launch_shinystan. In both
> cases my R terminal remains unresponsive with "Listening on...".
>
The same thing as above should apply here, although perhaps there are
certain errors that would prevent this from working. With which errors have
you noticed this behavior? The HMC related error in the other issue?

**Comment by colemonnahan** [comment]
@jgabry I am using emacs with ESS, which just opens an R terminal inside the text editor. I updated emacs and ESS and the first issue seems to be gone -- now when I forget to close it returns to R as it should.

However, on an error I still get the same issue and R locks up. When I run the same thing in RStudio it locks up but can recover more gracefully. So I guess this is more of an ESS thing not playing nicely with shiny?

**Comment by jgabry** [comment]
On Mon, Sep 12, 2016 at 1:06 PM, Cole Monnahan <notifications@github.com>
wrote:

> @jgabry <https://github.com/jgabry> I am using emacs with ESS, which just
> opens an R terminal inside the text editor. I updated emacs and ESS and the
> first issue seems to be gone -- now when I forget to close it returns to R
> as it should.
>
Ok glad that's working ok now.

> However, on an error I still get the same issue and R locks up. When I run
> the same thing in RStudio it locks up but can recover more gracefully. So I
> guess this is more of an ESS thing not playing nicely with shiny?
>
Hmm, I don't use ESS myself so I'm not sure but it wouldn't surprise me if
it didn't always play nicely with shiny. It would be nice if I could find a
way to avoid this issue though. I'll have to do some digging around to see
if I can figure out exactly what the source of the problem is.

**Comment by VeenDuco** [comment]
We are currently working on version 3.0 and hopefully this error will not occur anymore. Because of the new version we are currently closing old issues as a clean-up for version 3.0 such that we have a new overview of current open issues. If the issue persist is the new version please do let us know.

Best, Duco
