### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by george-githinji** [stan-dev/shinystan#150]
I get these errors while installing `shinystan` on `OS X. R 3.4`, The issue appears to be a dependency of `PKI package`. Any ideas on a workaround? 

```
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/Users/Shared/Jenkins/workspace/External-R-3.3.3/vendor/build/include -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include   -fPIC  -I/Users/Shared/Jenkins/workspace/External-R-3.3.3/vendor/build/include -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include  -c asn1.c -o asn1.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/Users/Shared/Jenkins/workspace/External-R-3.3.3/vendor/build/include -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include   -fPIC  -I/Users/Shared/Jenkins/workspace/External-R-3.3.3/vendor/build/include -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include  -c init.c -o init.o
In file included from init.c:1:
./pki.h:11:10: fatal error: 'openssl/err.h' file not found
#include <openssl/err.h>
         ^
1 error generated.
make: *** [init.o] Error 1
ERROR: compilation failed for package ‘PKI’
* removing ‘/Users/george/Library/R/3.4/library/PKI’
Warning in install.packages :
  installation of package ‘PKI’ had non-zero exit status
ERROR: dependency ‘PKI’ is not available for package ‘rsconnect’
* removing ‘/Users/george/Library/R/3.4/library/rsconnect’
Warning in install.packages :
  installation of package ‘rsconnect’ had non-zero exit status
ERROR: dependency ‘rsconnect’ is not available for package ‘shinystan’
* removing ‘/Users/george/Library/R/3.4/library/shinystan’
Warning in install.packages :
  installation of package ‘shinystan’ had non-zero exit status
```

**Comment by biorelated** [comment]
I  have resolved this issue by specifying the location for ssl  in a .makevars file

```
CFLAGS= -g -O3 -Wall -pedantic -mtune=native -I/usr/local/opt/openssl/include
CXXFLAGS= -g -O3 -Wall -pedantic -mtune=native -I/usr/local/opt/openssl/include
LDFLAGS= -L/usr/local/opt/openssl/lib
```
You might want to add this to the documentation section of the installation  on OS X (Mac OS )

**Comment by jerlich** [comment]
I had a similar issue with libintl from gettext. Similar solution. Add 
`LDFLAGS= -L/usr/local/opt/gettext/lib`

**Comment by jgabry** [comment]
Thanks for the tip. I need to add a troubleshooting section to the
installation instructions and I'll include this.

**Comment by jerlich** [comment]
I actually had a lot of errors in installation on ubuntu. All of them were fixable.
Some complained about missing libraries/dev packages that needs to be installed on the system. 
there is a well known problem with igraph (which can be installed directly from github instead of CRAN for a fix. ). I did find that if one actually reads the error messages the fixes are generally clear to someone who understands includes and libraries. But to a linux newbie it might be quite daunting.

**Comment by VeenDuco** [comment]
We are currently working on version 3.0 and hopefully this error will not occur anymore. Because of the new version we are currently closing old issues as a clean-up for version 3.0 such that we have a new overview of current open issues. If the issue persist is the new version please do let us know.

Best, Duco
