### ISSUE TITLE
Shinystan error in rstan

### ISSUE THREAD

**Issue by nickg7999** [stan-dev/shinystan#164]
Running stan and rstan with RStudio on Windows 7 Pro. Today I just updated and installed shinystan. When I then tried loading shinystan vial
library("shinystan")
I received the error message: 
Error: package or namespace load failed for ‘shinystan’ in library.dynam(lib, package, package.lib):
 DLL ‘stringi’ not found: maybe not installed for this architecture?
In addition: Warning message:
package ‘shinystan’ was built under R version 3.5.2 
I receive the same error when trying to load shinystan from the R console.

Yesterday I ran the same software at home on a Windows 7 laptop and did not encounter any such error.
rstan runs fine on both computers.

Nickg

**Comment by VeenDuco** [comment]
Apologies for the very late reaction. We are currently working on version 3.0 and hopefully this error will not occur anymore. Because of the new version we are currently closing old issues as a clean-up for version 3.0 such that we have a new overview of current open issues. If the issue persist is the new version please do let us know.

Best, Duco
