### ISSUE TITLE
Web browser view bug

### ISSUE THREAD

**Issue by WalterCh** [stan-dev/shinystan#170]
I am just starting to learn how to use shinystan and at the time I run the code: 'launch_shinystan(model)' or even when I run 'launch_shinystan_demo()' I get the same bugged web browser page. I have tried to reinstall shinystan or even just restarting the session in RStudio, but nothing has chanched.

![bug](https://user-images.githubusercontent.com/38228086/59929147-d4f3b700-9405-11e9-8e0e-32eef7fd3740.png)

![bug2](https://user-images.githubusercontent.com/38228086/59929526-9ad6e500-9406-11e9-8b91-08afe59a7ff1.png)

**Comment by VeenDuco** [comment]
Apologies for the late reaction. We are currently working on version 3.0 and hopefully this error will not occur anymore. Because of the new version we are currently closing old issues as a clean-up for version 3.0 such that we have a new overview of current open issues. If the issue persist is the new version please do let us know.

Best, Duco
