### ISSUE TITLE
Error using launch_shinystan when using options(encoding = "UFT-8")

### ISSUE THREAD

**Issue by willemvdb42** [stan-dev/shinystan#171]
Hi,

I'm trying to launch shinystan on a `brmsfit` model: `launch_shinystan(myModel)`. However this produces the following error:

> Warning in readLines(path, warn = FALSE, encoding = "UTF-8") :
  invalid input found on input connection 'html/mcse.html'
Warning: Error in sub: input string 1 is invalid UTF-8
  [No stack trace available]

The problem is solved by first setting the encoding to the native system encoding using `options(encoding = "native.enc")` and then using `launch_shinystan(myModel)` again.

I can reproduce this problem simply by changing the encoding back to UTF-8, i.e. first running `options(encoding = "UTF-8")` and then using `launch_shinystan(myModel)`.

I'm not sure where but my suspicion is that an `encoding` argument in a function call is not properly set. (But I could be wrong.) In any case I first posted this as a `brms` issue but there they told me it's probably related to `shinystan`.

**Comment by VeenDuco** [comment]
Apologies for the late reaction. We are currently working on version 3.0 and hopefully this error will not occur anymore.  Because of the new version we are currently closing old issues as a clean-up for version 3.0 such that we have a new overview of current open issues. If the issue persist is the new version please do let us know. 

Best, Duco
