### ISSUE TITLE
Reading from CmdStan with warmup excluded

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/shinystan#21]
It appears as if extract_shinystan_object.R expects nWarmup to be a positive value, but that might not be the case outside of RStan where by default the warmup iterations are not written to the .csv files

See https://groups.google.com/d/msg/stan-users/9RWqXbED-po/-SbJ_Rg2DI0J

**Comment by jgabry** [comment]
Thanks Ben. I'm on it.

**Comment by jgabry** [comment]
Ugh, these .csv files are annoying. And read_stan_csv constructs a stanfit object with different components in the stan_args slot if your csv comes from cmdstan vs if the csv comes from rstan.

**Comment by bgoodri** [comment]
Yes, read _ stan _ csv needs to be improved and the csv needs to be
improved but you probably have to hack something together for now.

**Comment by jgabry** [comment]
Yeah, until then I'll at least get it working even if it's not ideal.

**Comment by jgabry** [comment]
Ok I think it will actually work if I use stanfit@sim$warmup2 instead of stanfit@sim$warmup when stanfit is generated by read_stan_csv(csv from cmdstan). At least with that change I can get it working with Seth's csv. I responded on stan-users with instructions for installing shinyStan from the branch with this fix so we'll see if it works for him.
