### ISSUE TITLE
Latex export is not affected by Decimal places

### ISSUE THREAD

**Issue by hoanguc3m** [stan-dev/shinystan#69]
In Posterial summary statistics, I want to export latex format using "Decimal places" for 3 digits, however, the result always stays at 2 digits. Is there any temporary alternative now? Thanks

**Comment by jgabry** [comment]
Thanks for pointing this out. The next release of shinyStan (v1.1.0) should be ready later this week or next week and we'll include a fix for this bug. 

You have good timing though, because I'll be fixing some other small bugs in this afternoon and I'll add this one to the list. Once there's a branch containing the bugfix I'll reply again and let you know so you can install shinyStan from that branch if you don't want to wait until the official 1.1.0 release.

**Comment by jgabry** [comment]
@hoanguc3m As far as I can tell this problem is now fixed in the `develop` branch and it will be included in version 1.1.0 when it's released (soon). In the meantime, if you want to try it now you can install shinyStan from the `develop` branch, which should only require running the following two lines of code in R

     # First restart R and make sure the shinyStan package isn't loaded.
    devtools::install_github("jgabry/shinyBS", ref = "shinyBS_for_shinyStan")
    devtools::install_github("stan-dev/shinystan", ref = "develop", build_vignettes = TRUE)

If you have trouble installing it let me know. 

I'm going to close this issue for now, but if the problem persists even after you install the new version please reopen the issue and let us know.
