### ISSUE TITLE
pairs plot

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#9]
From **@mhandreae**:

I think it would be nice to have a ggpairs plot to quickly assess the correlation of all beta regression coefficients quickly and efficiently for simple models for the beginning or intermediate user of Stan.

Copied from original issue: jgabry/SHINYstan#30

**Comment by bgoodri** [comment]
This should be prioritized now that rstan 2.7.0 has new default settings. I think of it primarily as a sampling diagnostic rather than a way of visualizing `cor(as.matrix(stanfit))`. Anyway, as described at the end of the documentation, it now splits the lower-triangle from the upper-triangle by median `accept_stat__` and overplots the divergent transitions (in red) and the transitions where it exceeds max_treedepth (in yellow). So, you can see whether the problems are concentrated in the tails or near the mode and which element(s) of the `control` list you need to tweak.

**Comment by jgabry** [comment]
Cool. I agree 100%. The problem I was having before was that it was really
really slow to produce the pairs plots. Is the new function more efficient?

**Comment by bgoodri** [comment]
No

**Comment by bgoodri** [comment]
It is not so slow if you select a reasonably small number of parameters and
if you select an unreasonably large number of parameters it is both slow
and impossible to visualize anything.

**Comment by bob-carpenter** [comment]
That sounds great --- I like the clear delineation of intent.

How would you recommend visualizing the correlations?

- Bob

**Comment by bob-carpenter** [comment]
It does take a long time if there are more than a handful of
variables.  I killed a live demo in Sydney by forgetting to turn
off pairs() in the script and upping the predictors to 200 or so.

So maybe it should just do the first 5 parameters or something by
default with a warning to the user that if they want more, they can
specify the parameters explicitly?

- Bob

**Comment by bgoodri** [comment]
Well, you could use pairs to visualize correlations or you could just do
cor(as.matrix(stanfit)) and see the numbers. But posterior correlation
isn't that interesting, per se, for HMC. Combined with changing variance,
it is something to worry about but if that is a concern, then it will
probably be manifested in transitions that diverge or exceed max_treedepth,
both of which are now evident from the pairs plot. Richard's version of the
pairs plot puts scatterplots in the upper triangle and the correlation
rounded to two digits in the lower triangle but to me, that makes it seem
as if there are some values of the bivariate correlation that the user
should freak out about.

**Comment by bgoodri** [comment]
Perhaps shinystan should not do all variables by default because it is easy
to select variables from a list before the plot fires. But for rstan I
worry that if it just does the first 5, then people will say "everything
looks okay" and move on. You really need to be looking at lp__ and
hyperparameters more than a bunch of regression coefficients.

**Comment by bob-carpenter** [comment]
I agree that your plot's more helpful diagnostically overall.

I think it helps diagnose non-identifiability issues and the
posterior scatterplot's interesting to see in its own right to
understand how a well-formulated model's variables relate to one
another.

I don't care about seeing the linear correlation as much as
I want to see how the variables relate in the posterior.  Of course
in ShinyStan we can do it with three variables, which is super cool,
but we want O(N^3) plots even less than we want O(N^2) ones.

- Bob

**Comment by betanalpha** [comment]
I think of these plots as not being so much diagnostic
but rather exploratory.  Counting n_divergent and
histogram’ing max_treedepth provide the immediate
diagnostics but the pairs plots are a great first step
towards identifying exactly what is causing those
diagnostics to fail.  This means that they should 
require at least some thought from the user, and
I would personally be fine with pairs requiring
that the user specify variables explicitly (based
on, for example, prior suspicion).
